for文で$iが1~10までループするたびに1づつ足す処理を提出します
yuta10200831/-docker-template-3.- pull request #1
Opened 2023-07-08 12:45 UTC by yuta10200831

## 作業対象
作業をした教材のURL or 作成したページのURLなどを記載する
[作業をした教材のURL]
https://www.notion.so/3-c4f781612e9a411ab616bef056fdac28
[作成したページのURL(index.php)]
http://localhost:8080/

## 作業詳細
PHP基礎　配列の課題
for文で$iが1~10までループするたびに1づつ足す処理を書きました。
そして、ループするたび配列に$iを代入する処理を追記。
for文処理の終了後、配列の値の合計を出力するようにしました。
<img width="1735" alt="スクリーンショット 2023-07-08 21 43 17" src="https://github.com/yuta10200831/-docker-template-3.-/assets/124555669/3ca3d711-93f5-4d94-b14e-f8d2c2e8fc98">

2023-07-09 09:02 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2023-07-09 09:02 UTC, KatsuyaTanaka95 commented on src/public/index.php
> +  for($i = 1; $i < 10; $i++) {
1~10までにしましょう！！

2023-07-09 09:02 UTC, KatsuyaTanaka95 commented on src/public/index.php
> +  $numbers[] = $i;
インデントを整えましょう！！

2023-07-09 15:52 UTC, yuta10200831 commented on src/public/index.php
> +  for($i = 1; $i < 10; $i++) {
修正しました！

2023-07-09 15:52 UTC, yuta10200831 commented on src/public/index.php
> +  $numbers[] = $i;
修正しました！

2023-07-09 15:57 UTC, yuta10200831 commented
1~10までに変更、インデントの修正をしました！
ご確認宜しくお願いします。

2023-07-10 02:29 UTC, KatsuyaTanaka95 approved these changes
ご修正ありがとうございます！
mergeいただけると助かります！🙆🙋😊🌟💫

ちなみに、6,7行目の位置は、2行目の位置と同じOKですよ！！😊

```
    $totalNumber = array_sum($numbers);
    echo $totalNumber;

```

2023-07-10 12:49 UTC, merged